### ISSUE TITLE
rename tag set by deply workflow

### ISSUE THREAD

**Issue by weefuzzy** [flucoma/fluid.waveform#13]
Currently it seems to be `main` which makes git confused when you try and checkout `main`

**Comment by jamesb93** [comment]
Oh that's bad. What should we call it?

**Comment by weefuzzy** [comment]
`build`?

**Comment by jamesb93** [comment]
imaginative! I'll change this tomorrow morning when I'm not error prone coding.

**Comment by jamesb93** [comment]
Solved in #14
