### ISSUE TITLE
Integrating with the flucoma-max

### ISSUE THREAD

**Issue by jamesb93** [flucoma/fluid.waveform#5]
How can we integrate this smoothly into the build process of flucoma-max? It's becoming incredibly useful for teaching so I think it needs to find its way there sooner rather than later :)

J

**Comment by weefuzzy** [comment]
We can add a FetchContent block like with the other dependencies; or we just manually include.

**Comment by jamesb93** [comment]
Pending PR #6 and maybe some github-action-fu maybe we could make there be a rolling release on commits that flucoma-max pulls from?

I could sort out the actions if you were up for sticking in a FetchContent block?

**Comment by weefuzzy** [comment]
Aye. It probably makes sense to do a CI build 'here' (and, uh, maybe some tests) and have flucoma-max pull from releases, rather than doing a clone etc. That way we keep all the babel etc. nicely cordoned off in here.

**Comment by jamesb93** [comment]
Cool, I can do that this eve and have it all ready for you m'lord.
